[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v5.0.0-esp32dev_debug-308391d-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v5.0.0-esp32dev_debug-308391d-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
