[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v3.1.1-esp32dev_debug-f2c0d00-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v3.1.1-esp32dev_debug-f2c0d00-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
