[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.4.5-esp32s3_debug-da92fd2-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.4.5-esp32s3_debug-da92fd2-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
