[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.4.2-esp32s3_debug-e4c9671-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.4.2-esp32s3_debug-e4c9671-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
