[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v2.1.2-esp32dev_debug-634bfa0-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v2.1.2-esp32dev_debug-634bfa0-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
