[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v1.11.4-esp32dev_debug-f66a3e9-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v1.11.4-esp32dev_debug-f66a3e9-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
