[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.4.4-esp32s3_debug-896aec7-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.4.4-esp32s3_debug-896aec7-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
