[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v4.5.7-esp32dev_debug-c9e4acc-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v4.5.7-esp32dev_debug-c9e4acc-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
