[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v4.1.0-esp32dev_debug-4fafe44-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v4.1.0-esp32dev_debug-4fafe44-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
