[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.2.3-esp32s3_debug-53035ab-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.2.3-esp32s3_debug-53035ab-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
