[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v2.0.0-esp32dev_debug-d4e4607-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v2.0.0-esp32dev_debug-d4e4607-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
