[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.2.2-esp32s3_debug-340c4f4-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.2.2-esp32s3_debug-340c4f4-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
