[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.4.0-esp32s3_debug-1b133b5-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.4.0-esp32s3_debug-1b133b5-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
