[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v1.11.0-esp32dev_debug-73fdd34-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v1.11.0-esp32dev_debug-73fdd34-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
