[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v4.5.6-esp32dev_debug-f07add0-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v4.5.6-esp32dev_debug-f07add0-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
