[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.5.1-esp32s3_debug-9f0f79c-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.5.1-esp32s3_debug-9f0f79c-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
