[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.3.2-esp32s3_debug-c08ee58-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.3.2-esp32s3_debug-c08ee58-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
