[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v1.10.1-esp32dev_debug-d93da61-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v1.10.1-esp32dev_debug-d93da61-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
