[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v1.12.0-esp32dev_debug-2119cb3-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v1.12.0-esp32dev_debug-2119cb3-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
