[wokwi]
version = 1
elf = ".pio/build/esp32dev_debug/EasyNetworkManager-v4.0.0-esp32dev_debug-6455bd4-main.elf"
firmware = ".pio/build/esp32dev_debug/EasyNetworkManager-v4.0.0-esp32dev_debug-6455bd4-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
