[wokwi]
version = 1
elf = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.4.1-esp32s3_debug-2541372-main.elf"
firmware = ".pio/build/esp32s3_debug/EasyNetworkManager-v5.4.1-esp32s3_debug-2541372-main.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
